[phases]
setup = """
sdkmanager --install 'platform-tools' 'platforms;android-29' 'build-tools;29.0.3' 'emulator' 'system-images;android-29;default;x86_64'
"""
[variables]
ANDROID_HOME = "/root/.android/sdk"
#test